In [121]:
import pandas as pd
import numpy as np

In [122]:
df=pd.read_csv("dirty_cafe_sales (1).csv")

df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [123]:
df.info()
print(df.dtypes)
print("Rows And Columns: ",df.shape)

df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB
Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object
Rows And Columns:  (10000, 8)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [124]:
print("Missing values:\n")
print(df.isnull().sum())

Missing values:

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [125]:
print("Duplicate Rows: ",df.duplicated().sum())
df.drop_duplicates(inplace=True)

Duplicate Rows:  0

In [126]:
df.replace(["ERROR","UNKNOWN"],np.nan,inplace=True)
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [127]:
df["Transaction Date"]=pd.to_datetime(df["Transaction Date"],errors="coerce")

In [128]:
print(df.dtypes)

Transaction ID              object
Item                        object
Quantity                    object
Price Per Unit              object
Total Spent                 object
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
dtype: object

In [135]:
numeric_cols=["Quantity","Price Per Unit","Total Spent"]

for col in numeric_cols:
    df[col]=pd.to_numeric(df[col],errors="coerce")
    df[col]=df[col].fillna(df[col].median())

In [136]:
print(df.dtypes)

Transaction ID              object
Item                        object
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
dtype: object

In [138]:
categorical_cols=["Item","Payment Method","Location"]
for col in categorical_cols:
    mode=df[col].mode(dropna=True)

    if not mode.empty:
       df[col]=df[col].fillna(mode[0])

In [139]:
df["Transaction Date"]=pd.to_datetime(df["Transaction Date"],errors="coerce")
df["Transaction Date"]=df["Transaction Date"].ffill()

In [140]:

categorical_cols=["Item","Payment Method","Location"]
for col in categorical_cols:
    df[col].fillna(df[col].mode()[0])

In [141]:
print(df.isnull().sum())
df.info()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              10000 non-null  object
 2   Quantity          10000 non-null  float64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 625.1+ KB

In [142]:
df.to_csv("Cleaned_cafe_sales.csv",index=False)
df.head(),df.tail(),df.sample(5)

(  Transaction ID    Item  Quantity  Price Per Unit  Total Spent  \
 0    TXN_1961373  Coffee       2.0             2.0          4.0
 1    TXN_4977031    Cake       4.0             3.0         12.0
 2    TXN_4271903  Cookie       4.0             1.0          8.0
 3    TXN_7034554   Salad       2.0             5.0         10.0
 4    TXN_3160411  Coffee       2.0             2.0          4.0

    Payment Method  Location Transaction Date
 0     Credit Card  Takeaway       2023-09-08
 1            Cash  In-store       2023-05-16
 2     Credit Card  In-store       2023-07-19
 3  Digital Wallet  Takeaway       2023-04-27
 4  Digital Wallet  In-store       2023-06-11  ,
      Transaction ID      Item  Quantity  Price Per Unit  Total Spent  \
 9995    TXN_7672686    Coffee       2.0             2.0          4.0
 9996    TXN_9659401     Juice       3.0             3.0          3.0
 9997    TXN_5255387    Coffee       4.0             2.0          8.0
 9998    TXN_7695629    Cookie       3.0             3.0          3.0
 9999    TXN_6170729  Sandwich       3.0             4.0         12.0

       Payment Method  Location Transaction Date
 9995  Digital Wallet  Takeaway       2023-08-30
 9996  Digital Wallet  Takeaway       2023-06-02
 9997  Digital Wallet  Takeaway       2023-03-02
 9998  Digital Wallet  Takeaway       2023-12-02
 9999            Cash  In-store       2023-11-07  ,
      Transaction ID    Item  Quantity  Price Per Unit  Total Spent  \
 7738    TXN_5065748    Cake       5.0             3.0         15.0
 4891    TXN_6540415    Cake       5.0             3.0         15.0
 9004    TXN_3388908  Cookie       4.0             3.0          4.0
 1057    TXN_7894514    Cake       1.0             3.0          3.0
 4872    TXN_9843421   Juice       3.0             3.0          9.0

       Payment Method  Location Transaction Date
 7738     Credit Card  In-store       2023-07-19
 4891  Digital Wallet  Takeaway       2023-05-27
 9004  Digital Wallet  Takeaway       2023-11-22
 1057  Digital Wallet  Takeaway       2023-09-25
 4872  Digital Wallet  In-store       2023-09-06  )